//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceMgmtDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tbl_users
    {

        public int user_id { get; set; }
        [Remote("ValidationError", "Insurance",HttpMethod ="post", ErrorMessage ="User Name Already Exists")]
        public string user_name { get; set; }
        public Nullable<int> group_function_id { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^\da-zA-Z]).{8,15}$", ErrorMessage = "Password must be between 6 and 20 characters and contain one uppercase letter, one lowercase letter, one digit and one special character.")]
        public string password { get; set; }
        public string role_name { get; set; }
        public Nullable<int> advisor_id { get; set; }
        [DataType(DataType.EmailAddress)]
        public string emailid { get; set; }
        public string contact_number { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public string display_name { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
    }
}
