//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceMgmtDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_advisor
    {
        public int advisor_id { get; set; }
        public string representative_number { get; set; }
        [Required]
        public string advisor_code { get; set; }
        [Required]
        public string advisor_name { get; set; }
        public Nullable<System.DateTime> date_of_appointment { get; set; }
        public Nullable<int> personal_info_id { get; set; }
        public Nullable<int> contact_details_id { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> promoted_date { get; set; }
    
        public string activity { get; set; }
        public Nullable<int> advisor_exp_level_id { get; set; }
        public Nullable<System.DateTime> left_ceased { get; set; }
        public Nullable<System.DateTime> joined { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        [Required]
        public string status { get; set; }
        [Required]
        public virtual tbl_advisor_experience_level tbl_advisor_experience_level { get; set; }
    }
}
