//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceMgmtDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_advisor_experience_level
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_advisor_experience_level()
        {
            this.tbl_advisor = new HashSet<tbl_advisor>();
        }
    
        public int advisor_exp_level_id { get; set; }
        public string advisor_exp_level { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> modified_on { get; set; }
        public Nullable<int> modified_by { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_advisor> tbl_advisor { get; set; }
    }
}
